---
- name: Install a plugin
  community.docker.docker_plugin:
    plugin_name: grafana/loki-docker-driver:latest
    state: present
    alias: loki

- name: Enable the plugin
  community.docker.docker_plugin:
    plugin_name: grafana/loki-docker-driver:latest
    state: enable

- name: Restart docker daemon
  ansible.builtin.service:
    name: docker
    state: restarted
  become: true
