---
docker_nats__name: nats
docker_nats__image: nats:latest
docker_nats__port: 4222
docker_nats__clustering_port: 6222
docker_nats__monitoring_port: 8222

docker_nats__network_mode:
docker_nats__networks: []
docker_nats__remove_existing_container: yes

docker_nats__env:
  
# Do not change
docker_nats__ports:
  - "{{ docker_nats__port }}:4222"
  - "{{ docker_nats__clustering_port }}:6222"
  - "{{ docker_nats__monitoring_port }}:8222"
