---
- name: Remove existing {{ container_name }} container
  community.docker.docker_container:
    name: "{{ container_name }}"
    state: absent
  when: remove_existing_container

- name: Run {{ container_name }} container
  community.docker.docker_container:
    name: "{{ container_name }}"
    image: "{{ image }}"
    restart_policy: "{{ restart_policy }}"
    command: "{{ command }}"
    volumes: "{{ volumes }}"
    entrypoint: "{{ entrypoint }}"
    network_mode: "{{ network_mode }}"
    networks: "{{ networks }}"
    expose: "{{ ports }}"
    ports: "{{ ports }}"
    env: "{{ env }}"
