---
- name: prepare application 'api'
  hosts: 
    - dev
    - stable
    - prod
  gather_facts: true
  become: true
  vars:
    docker_network: workspace
  roles:
    - role: grzegorznowak.nvm_node
      nvm_node_version: '20.9.0'

    - role: riemers.ansible-gitlab-runner
      gitlab_runner_coordinator_url: https://gitlab.example.com/
      gitlab_runner_registration_token: 'registration-token-here'
      gitlab_runner_runners:
        - name: 'Shell runner'
          executor: shell
          gitlab_runner_name: 'alpine'
          tags:
            - "{{ gitlab_runner_name }}"

    - role: geerlingguy.docker
      docker_users: ["ubuntu", "gitlab-runner"]

    - role: geerlingguy.node_exporter

    - role: create_docker_network

    - role: docker_loki_plugin

    - role: start_docker
      container_name: postgres
      image: postgres:15.4
      networks: 
        - name:  "{{ docker_network }}" 
      remove_existing_container: yes
      env:
        POSTGRES_USER: "{{ postgres_user }}"
        POSTGRES_PASSWORD: "{{ postgres_password }}"
        POSTGRES_DB: "{{ postgres_db }}"
      volumes:
        - "{{ postgres_volume }}"
      ports: 
        - 5432:5432
