---
- name: Prepare application 'api'
  hosts:
    - dev
    - stable
    - prod
  gather_facts: true
  become: true
  vars:
    docker_network__name: workspace
  roles:
    - role: grzegorznowak.nvm_node
      nvm_node_version: 20.9.0

    - role: riemers.ansible-gitlab-runner
      gitlab_runner_coordinator_url: https://gitlab.example.com/
      gitlab_runner_registration_token: registration-token-here
      gitlab_runner_runners:
        - name: Shell runner
          executor: shell
          gitlab_runner_name: alpine
          tags:
            - "{{ gitlab_runner_name }}"

    - role: geerlingguy.docker
      docker_users: [ubuntu, gitlab-runner]

    - role: geerlingguy.node_exporter

    - role: docker_network

    - role: docker_loki_plugin

    - role: docker
      docker__container_name: postgres
      docker__image: postgres:15.4
      docker__networks:
        - name: "{{ docker_network__name }}"
      docker__remove_existing_container: true
      docker__env:
        POSTGRES_USER: "{{ postgres_user }}"
        POSTGRES_PASSWORD: "{{ postgres_password }}"
        POSTGRES_DB: "{{ postgres_db }}"
      docker__volumes:
        - "{{ postgres_volume }}"
      docker__ports:
        - 5432:5432
