---
- name: Start local
  hosts: local
  become: true
  gather_facts: false
  vars:
    docker_network__name: workspace
  roles:
    - role: docker_network

    - role: docker
      docker__container_name: nats
      docker__image: nats:latest
      docker__command: --jetstream --store_dir /data/nats-server/ -m 8222
      docker__volumes:
        - /mnt/nats:/data/nats-server/jetstream
      docker__networks:
        - name: "{{ docker_network__name }}"
      docker__remove_existing_container: true
      docker__ports:
        - 4222:4222
        - 6222:6222
        - 8222:8222

    - role: docker
      docker__container_name: prometheus-nats-exporter
      docker__image: natsio/prometheus-nats-exporter:latest
      docker__networks:
        - name: "{{ docker_network__name }}"
      docker__remove_existing_container: true
      docker__entrypoint:
        - /prometheus-nats-exporter
        - -varz
        - -channelz
        - -connz
        - -healthz
        - -leafz
        - -routez
        - -serverz
        - -subz
        - -gatewayz
        - -jsz=all
        - http://nats:8222/
      docker__ports:
        - 8223:7777

    - role: docker
      docker__container_name: postgres
      docker__image: postgres:13.1
      docker__networks:
        - name: "{{ docker_network__name }}"
      docker__remove_existing_container: false
      docker__env:
        POSTGRES_USER: postgres
        POSTGRES_PASSWORD: postgres
        POSTGRES_DB: postgres
      docker__volumes:
        - /var/lib/postgres:/var/lib/postgresql/data
      docker__ports:
        - 5432:5432

    - role: grafana
      grafana__networks:
        - name: "{{ docker_network__name }}"
      grafana__remove_existing_container: true
      grafana__ports:
        - 3050:3000
      grafana__config_template: "{{ playbook_dir }}/templates/grafana/config.ini.j2"
      grafana__datasource_template: "{{ playbook_dir }}/templates/grafana/datasource.yml.j2"
      grafana__dashboards_template: "{{ playbook_dir }}/templates/grafana/dashboards.yaml.j2"
      grafana__dashboards_dir_source: "{{ playbook_dir }}/templates/grafana/dashboards"

    - role: prometheus
      prometheus__networks:
        - name: "{{ docker_network__name }}"
      prometheus__remove_existing_container: true
      prometheus__template: "{{ playbook_dir }}/templates/prometheus/prometheus-local.yml.j2"

    - role: loki
      loki__networks:
        - name: "{{ docker_network__name }}"
      loki__remove_existing_container: true
      loki__ports:
        - 3100:3100
      loki__config_template: "{{ playbook_dir }}/templates/loki/local-config.yaml.j2"

    - role: tempo
      tempo__networks:
        - name: "{{ docker_network__name }}"
      tempo__remove_existing_container: true
      tempo__config_template: "{{ playbook_dir }}/templates/tempo/tempo.yaml.j2"

    - role: otel_collector
      otel_collector__networks:
        - name: "{{ docker_network__name }}"
      otel_collector__remove_existing_container: true
      otel_collector__config_template: "{{ playbook_dir }}/templates/otel-collector/config.yaml.j2"
