---
- name: start local
  hosts: local
  gather_facts: false
  vars:
    docker_network: workspace
  roles:
    - role: create_docker_network

    - role: start_docker
      container_name: nats
      image: nats:latest
      command: "--jetstream --store_dir /data/nats-server/"
      volumes:
        - "/var/lib/nats:/data/nats-server/jetstream"
      networks: 
        - name:  "{{ docker_network }}" 
      remove_existing_container: no
      ports: 
        - 4222:4222
        - 6222:6222
        - 8222:8222

    - role: start_docker
      container_name: postgres
      image: postgres:13.1
      networks: 
        - name:  "{{ docker_network }}" 
      remove_existing_container: no
      env:
        POSTGRES_USER: "postgres"
        POSTGRES_PASSWORD: "postgres"
        POSTGRES_DB: "postgres"
      volumes:
        - "/var/lib/postgres:/var/lib/postgresql/data"
      ports: 
        - 5432:5432