---
- name: Prepare nats
  hosts: nats
  gather_facts: false
  become: true
  vars:
    docker_network__name: workspace
  roles:
    - role: geerlingguy.docker
      docker_users: [ubuntu]

    - role: docker_network

    - role: docker
      docker__container_name: nats
      docker__image: nats:latest
      docker__command: --jetstream --store_dir /data/nats-server/ -m 8222
      docker__volumes:
        - /mnt/nats:/data/nats-server/jetstream
      docker__networks:
        - name: "{{ docker_network__name }}"
      docker__remove_existing_container: true
      docker__ports:
        - 4222:4222
        - 6222:6222
        - 8222:8222

    - role: docker
      docker__container_name: prometheus-nats-exporter
      docker__image: natsio/prometheus-nats-exporter:latest
      docker__networks:
        - name: "{{ docker_network__name }}"
      docker__remove_existing_container: true
      docker__entrypoint:
        - /prometheus-nats-exporter
        - -varz
        - -channelz
        - -connz
        - -healthz
        - -leafz
        - -routez
        - -serverz
        - -subz
        - -gatewayz
        - -jsz=all
        - http://nats:8222/
      docker__ports:
        - 8223:7777
