---
- name: Remove existing {{ docker_nats__name }} container
  docker_container:
    name: "{{ docker_nats__name }}"
    state: absent
  when: docker_nats__remove_existing_container

- name: Run {{ docker_nats__name }} container
  docker_container:
    name: "{{ docker_nats__name }}"
    image: "{{ docker_nats__image }}"
    restart_policy: always
    command: ["--jetstream"]
    network_mode: "{{ docker_nats__network_mode }}"
    networks: "{{ docker_nats__networks }}"
    expose:
      - "{{ docker_nats__ports }}"
    ports: "{{ docker_nats__ports }}"
    env: "{{ docker_nats__env }}"
