---
- name: Remove existing {{ docker_app__name }} container
  docker_container:
    name: "{{ docker_app__name }}"
    state: absent
  when: docker_app__remove_existing_container

- name: Run {{ docker_app__name }} container
  docker_container:
    name: "{{ docker_app__name }}"
    image: "{{ docker_app__image }}"
    restart_policy: always
    network_mode: "{{ docker_app__network_mode }}"
    networks: "{{ docker_app__networks }}"
    expose:
      - "{{ docker_app__ports }}"
    ports: "{{ docker_app__ports }}"
    env: "{{ docker_app__env }}"
